### ISSUE TITLE
Can't handle non-public stream

### ISSUE THREAD

**Issue by Fronti** [cccc/plugin.video.media-ccc-de#13]
Hi,

the plugin seems to fail to load the "live streaming" directory when there is a non-public stream, like the one in Hall1 right now, as it can't find the stream urls.

Relevant part of Kodi's debug log:

````
`21:35:19.146 T:1107276872   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:35:19.645 T:1541526136   DEBUG: [plugin.video.media-ccc-de][routing] Dispatching to 'show_live', args: {}
21:35:20.168 T:1541526136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'list' object has no attribute 'items'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 196, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 124, in show_live
                                                data = http.fetch_live()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/resources/lib/http.py", line 46, in fetch_live
                                                return Streams(req.json())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/resources/lib/stream.py", line 12, in __init__
                                                for elem in group['rooms']]
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/resources/lib/stream.py", line 19, in __init__
                                                for urlname, urldata in stream["urls"].items():
                                            AttributeError: 'list' object has no attribute 'items'
                                            -->End of Python script error report<--
21:35:20.180 T:1107276872   DEBUG: ------ Window Init (DialogNotification.xml) ------`
````

**Comment by TobiX** [comment]
This was fixed server-side.
