### ISSUE TITLE
Live stream from 33c3 broken again

### ISSUE THREAD

**Issue by jkehne** [cccc/plugin.video.media-ccc-de#15]
Apparently, the plugin cannot find any rooms in the json returned. Yesterday, I was able to watch the fnord show just fine. Recordings also work fine. Could this be caused by the fix to #13?

Here is the stack trace:

```
11:48:36.223 T:140424425502464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 197, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 124, in show_live
                                                data = http.fetch_live(wants_insecure())
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/resources/lib/http.py", line 43, in fetch_live
                                                return Streams(req.json())
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/resources/lib/stream.py", line 12, in __init__
                                                for elem in group['rooms']]
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--

**Comment by jkehne** [comment]
Update: It just started working again.

**Comment by Azidburn** [comment]
The Format of the Livestream JSON was changed, it has more the one group.
I attached the broken JSON.

[v1.txt](https://github.com/cccc/plugin.video.media-ccc-de/files/676991/v1.txt)

**Comment by TobiX** [comment]
Fixed server-side by https://github.com/voc/streaming-website/commit/22bfef4aeca6f61d440fff9008f3074c5f1b28f4
