### ISSUE TITLE
Can't select "correct" stream anymore

### ISSUE THREAD

**Issue by TobiX** [cccc/plugin.video.media-ccc-de#8]
Since https://github.com/voc/media.ccc.de/commit/32e27e6814e1435e903f2b4a6ccecd729742327c was deployed on media.ccc.de, it has become impossible to select the right video (maximum number of audio streams, correct hd/sd distinction) for most events, since there isn't enough data to make a correct selection. See https://api.media.ccc.de/public/events/2212 for example: It has 5 videos: 3 mp4, 2 webm, all are "hd" and have language "en". There is clearly a problem with the data here...

**Comment by ebora** [comment]
Is this the same issue I'm seeing? 
I already changed to the development version you linked to here: [https://github.com/cccc/plugin.video.media-ccc-de/issues/5](url) because I couldn't access the subfolders. Subfolders are working again now, but I still can't view any of the several viedos I tried.
The error log says:

```
14:33:05 61945.906250 T:2667988000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('hd',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 167, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 91, in resolve_event
                                                want = recording_list(data, quality, format)
                                              File "/home/osmc/.kodi/addons/plugin.video.media-ccc-de/resources/lib/helpers.py", line 4, in recording_list
                                                recs = [Recording(elem) for elem in json]
                                              File "/home/osmc/.kodi/addons/plugin.video.media-ccc-de/resources/lib/helpers.py", line 14, in __init__
                                                self.hd = json['hd']
                                            KeyError: ('hd',)
                                            -->End of Python script error report<--
14:33:05 61946.031250 T:3025048112   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.media-ccc-de/event/2659]

**Comment by TobiX** [comment]
@ebora This seems to be a new (closely related) problem. The API is a bit in-flux right now (https://github.com/voc/media.ccc.de/commit/ac8f07636a1211c7dc2cabe3573e7faae106af0e), I'll release a new add-on when everything is settled.

**Comment by TobiX** [comment]
Fixed in new release.
