### ISSUE TITLE
Streaming not working on WETEK Play with OpenELEC 6.0.1

### ISSUE THREAD

**Issue by maxkes** [cccc/plugin.video.media-ccc-de#9]
Hi,

I can start the ccc-tv addon, but it's not possible to watch a stream. 

Kind regards, Max

Logfile is:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('display_mime_type',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 167, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 91, in resolve_event
                                                want = recording_list(data, quality, format)
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/resources/lib/helpers.py", line 4, in recording_list
                                                recs = [Recording(elem) for elem in json]
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/resources/lib/helpers.py", line 12, in __init__
                                                self.mime = json['display_mime_type']
                                            KeyError: ('display_mime_type',)
                                            -->End of Python script error report<--
20:45:32 T:3041021952   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.media-ccc-de/event/2856]

**Comment by TobiX** [comment]
This is a known bug (#7), fixed in trunk, you might want to update to a snapshot (http://is.gd/ccckodi) until I have pushed a new release.

**Comment by maxkes** [comment]
Ok, thanks for the quick reply!
